export type RiskOption = {
  label: string;
  value: string;
  pontos: number;
};

export type RiskQuestion = {
  codigo: string;
  secao: string;
  titulo: string;
  tipo: "text" | "textarea" | "select" | "number" | "date" | "multiselect";
  obrigatoria?: boolean;
  categoria: string;
  peso: number;
  opcoes?: RiskOption[];
  placeholder?: string;
};

export type QuestionnaireType = "middle" | "grandes_riscos";

export const QUESTIONNAIRES: Record<QuestionnaireType, RiskQuestion[]> = {
  middle: [
    {
      codigo: "proponente_razao_social",
      secao: "Proponente",
      titulo: "Razão social e CNPJ",
      tipo: "text",
      obrigatoria: true,
      categoria: "cadastro",
      peso: 1,
      placeholder: "Informe a razão social e o CNPJ",
    },
    {
      codigo: "proponente_atividade_principal",
      secao: "Proponente",
      titulo: "Qual a atividade principal desenvolvida?",
      tipo: "text",
      obrigatoria: true,
      categoria: "atividade",
      peso: 2,
      placeholder: "Descreva a atividade principal",
    },
    {
      codigo: "proponente_outras_atividades",
      secao: "Proponente",
      titulo: "Exerce outras atividades, inclusive em locais de terceiros?",
      tipo: "textarea",
      categoria: "atividade",
      peso: 2,
      placeholder: "Descreva os detalhes, se houver",
    },

    {
      codigo: "locais_enderecos",
      secao: "Locais Segurados",
      titulo: "Relação dos endereços dos locais segurados",
      tipo: "textarea",
      obrigatoria: true,
      categoria: "locais",
      peso: 2,
      placeholder: "Matriz, filiais, depósitos, lojas, fábricas etc.",
    },
    {
      codigo: "locais_atividade_valores_risco",
      secao: "Locais Segurados",
      titulo: "Atividade em cada local e valores em risco",
      tipo: "textarea",
      categoria: "locais",
      peso: 3,
      placeholder: "Informe atividade por local e valores em risco",
    },
    {
      codigo: "locais_condominio_logistico",
      secao: "Locais Segurados",
      titulo: "Algum local está em condomínio logístico ou parque industrial?",
      tipo: "select",
      obrigatoria: true,
      categoria: "exposicao",
      peso: 2,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 4 },
      ],
    },
    {
      codigo: "locais_atividades_auxiliares",
      secao: "Locais Segurados",
      titulo: "Algum local realiza atividades complementares ou auxiliares ao processo principal?",
      tipo: "select",
      obrigatoria: true,
      categoria: "operacao",
      peso: 2,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 3 },
      ],
    },
    {
      codigo: "locais_substancias_perigosas",
      secao: "Locais Segurados",
      titulo: "Existe armazenagem, movimentação, transporte, uso ou execução de trabalhos com substâncias tóxicas, corrosivas, inflamáveis ou explosivas?",
      tipo: "select",
      obrigatoria: true,
      categoria: "inflamaveis",
      peso: 4,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 9 },
      ],
    },
    {
      codigo: "locais_trabalho_quente",
      secao: "Locais Segurados",
      titulo: "Existe permissão para trabalho a quente?",
      tipo: "select",
      obrigatoria: true,
      categoria: "trabalho_quente",
      peso: 4,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 8 },
      ],
    },
    {
      codigo: "locais_caracteristica_construtiva",
      secao: "Locais Segurados",
      titulo: "Características construtivas do principal local",
      tipo: "select",
      obrigatoria: true,
      categoria: "construcao",
      peso: 5,
      opcoes: [
        { label: "Superior", value: "superior", pontos: 1 },
        { label: "Sólida", value: "solida", pontos: 3 },
        { label: "Mista", value: "mista", pontos: 7 },
        { label: "Inferior", value: "inferior", pontos: 10 },
      ],
    },
    {
      codigo: "locais_pir_pur_larocha",
      secao: "Locais Segurados",
      titulo: "Há edificações mistas ou inferiores e/ou com mais de 25% da construção em PIR, PUR ou lã de rocha?",
      tipo: "select",
      obrigatoria: true,
      categoria: "construcao",
      peso: 4,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 8 },
      ],
    },
    {
      codigo: "locais_construcao_temporaria",
      secao: "Locais Segurados",
      titulo: "Existe mais de 15% do valor em risco em construções temporárias, como vinilona?",
      tipo: "select",
      obrigatoria: true,
      categoria: "construcao",
      peso: 4,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 9 },
      ],
    },
    {
      codigo: "locais_manutencao",
      secao: "Locais Segurados",
      titulo: "O prédio e o conteúdo possuem plano de manutenção?",
      tipo: "select",
      obrigatoria: true,
      categoria: "manutencao",
      peso: 4,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 8 },
      ],
    },
    {
      codigo: "locais_tipo_manutencao",
      secao: "Locais Segurados",
      titulo: "A manutenção é terceirizada ou própria?",
      tipo: "select",
      categoria: "manutencao",
      peso: 2,
      opcoes: [
        { label: "Própria", value: "propria", pontos: 2 },
        { label: "Terceirizada", value: "terceirizada", pontos: 3 },
      ],
    },
    {
      codigo: "locais_transito_terceiros",
      secao: "Locais Segurados",
      titulo: "Nível de trânsito ou permanência de terceiros",
      tipo: "select",
      obrigatoria: true,
      categoria: "terceiros",
      peso: 3,
      opcoes: [
        { label: "Baixo", value: "baixo", pontos: 1 },
        { label: "Médio", value: "medio", pontos: 4 },
        { label: "Alto", value: "alto", pontos: 7 },
      ],
    },
    {
      codigo: "locais_gerador_emergencia",
      secao: "Locais Segurados",
      titulo: "Possui gerador de emergência?",
      tipo: "select",
      obrigatoria: true,
      categoria: "continuidade",
      peso: 3,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 6 },
      ],
    },

    {
      codigo: "protecional_avcb",
      secao: "Sistemas Protecionais",
      titulo: "Possui AVCB vigente?",
      tipo: "select",
      obrigatoria: true,
      categoria: "incendio",
      peso: 5,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 10 },
      ],
    },
    {
      codigo: "protecional_brigada",
      secao: "Sistemas Protecionais",
      titulo: "Possui Brigada de Incêndio com treinamento periódico?",
      tipo: "select",
      obrigatoria: true,
      categoria: "incendio",
      peso: 4,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 8 },
      ],
    },
    {
      codigo: "protecional_distancia_bombeiros",
      secao: "Sistemas Protecionais",
      titulo: "Distância do Corpo de Bombeiros mais próximo (km)",
      tipo: "number",
      obrigatoria: true,
      categoria: "incendio",
      peso: 3,
      placeholder: "Ex.: 5",
    },
    {
      codigo: "protecional_combate_incendio",
      secao: "Sistemas Protecionais",
      titulo: "Sistemas de detecção e combate a incêndio existentes",
      tipo: "multiselect",
      obrigatoria: true,
      categoria: "incendio",
      peso: 5,
      opcoes: [
        { label: "Extintores", value: "extintores", pontos: 1 },
        { label: "Hidrantes", value: "hidrantes", pontos: 1 },
        { label: "Mangotinhos", value: "mangotinhos", pontos: 1 },
        { label: "Sprinklers ou supressão automática", value: "sprinklers", pontos: 1 },
        { label: "Alarmes / detectores de fumaça", value: "alarmes", pontos: 1 },
      ],
    },
    {
      codigo: "protecional_roubo_furto",
      secao: "Sistemas Protecionais",
      titulo: "Proteções contra roubo e furto",
      tipo: "multiselect",
      categoria: "seguranca",
      peso: 4,
      opcoes: [
        { label: "Segurança patrimonial presencial", value: "seguranca_presencial", pontos: 1 },
        { label: "Alarme de intrusão", value: "alarme_intrusao", pontos: 1 },
        { label: "CFTV", value: "cftv", pontos: 1 },
        { label: "Sensores de presença", value: "sensores", pontos: 1 },
        { label: "Controle de acesso", value: "controle_acesso", pontos: 1 },
      ],
    },
    {
      codigo: "protecional_alagamento",
      secao: "Sistemas Protecionais",
      titulo: "Há sistemas de proteção para risco de alagamento?",
      tipo: "select",
      categoria: "alagamento",
      peso: 3,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 6 },
      ],
    },
    {
      codigo: "protecional_desmoronamento",
      secao: "Sistemas Protecionais",
      titulo: "Há sistemas de proteção para risco de desmoronamento?",
      tipo: "select",
      categoria: "estrutura",
      peso: 3,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 6 },
      ],
    },

    {
      codigo: "experiencia_sinistros_5anos",
      secao: "Experiência",
      titulo: "Algum local sofreu sinistros nos últimos 5 anos?",
      tipo: "select",
      obrigatoria: true,
      categoria: "historico",
      peso: 5,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 9 },
      ],
    },
    {
      codigo: "experiencia_potencial_reclamacao",
      secao: "Experiência",
      titulo: "Existe fato ou circunstância que possa gerar reclamação?",
      tipo: "select",
      obrigatoria: true,
      categoria: "historico",
      peso: 4,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 8 },
      ],
    },
  ],

  grandes_riscos: [
    {
      codigo: "proponente_nome_cnpj",
      secao: "Proponente",
      titulo: "Nome e CNPJ",
      tipo: "text",
      obrigatoria: true,
      categoria: "cadastro",
      peso: 1,
      placeholder: "Informe o nome empresarial e o CNPJ",
    },
    {
      codigo: "proponente_atividade_principal",
      secao: "Proponente",
      titulo: "Qual a atividade principal desenvolvida?",
      tipo: "text",
      obrigatoria: true,
      categoria: "atividade",
      peso: 2,
      placeholder: "Descreva a atividade principal",
    },
    {
      codigo: "proponente_outras_atividades",
      secao: "Proponente",
      titulo: "Exerce outras atividades, inclusive em locais de terceiros?",
      tipo: "textarea",
      categoria: "atividade",
      peso: 2,
      placeholder: "Descreva os detalhes, se houver",
    },
    {
      codigo: "proponente_inicio_operacoes",
      secao: "Proponente",
      titulo: "Data de início das operações",
      tipo: "date",
      obrigatoria: true,
      categoria: "atividade",
      peso: 2,
    },

    {
      codigo: "locais_enderecos",
      secao: "Locais Segurados",
      titulo: "Relação dos endereços dos locais segurados",
      tipo: "textarea",
      obrigatoria: true,
      categoria: "locais",
      peso: 2,
      placeholder: "Matriz, filiais, depósitos, lojas, fábricas etc.",
    },
    {
      codigo: "locais_endereco_principal",
      secao: "Locais Segurados",
      titulo: "Endereço do principal local ou do maior valor em risco",
      tipo: "text",
      obrigatoria: true,
      categoria: "locais",
      peso: 2,
      placeholder: "Informe o principal local",
    },
    {
      codigo: "locais_condominio_logistico",
      secao: "Locais Segurados",
      titulo: "Algum local está em condomínio logístico ou parque industrial?",
      tipo: "select",
      obrigatoria: true,
      categoria: "exposicao",
      peso: 2,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 4 },
      ],
    },
    {
      codigo: "locais_atividades_auxiliares",
      secao: "Locais Segurados",
      titulo: "Algum local realiza atividades complementares ou auxiliares ao processo principal?",
      tipo: "select",
      obrigatoria: true,
      categoria: "operacao",
      peso: 2,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 3 },
      ],
    },
    {
      codigo: "locais_substancias_perigosas",
      secao: "Locais Segurados",
      titulo: "Existe armazenagem, movimentação, transporte, uso ou execução de trabalhos com substâncias tóxicas, corrosivas, inflamáveis ou explosivas?",
      tipo: "select",
      obrigatoria: true,
      categoria: "inflamaveis",
      peso: 4,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 9 },
      ],
    },
    {
      codigo: "locais_trabalho_quente",
      secao: "Locais Segurados",
      titulo: "Existe permissão para trabalho a quente?",
      tipo: "select",
      obrigatoria: true,
      categoria: "trabalho_quente",
      peso: 4,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 8 },
      ],
    },
    {
      codigo: "locais_caracteristica_construtiva",
      secao: "Locais Segurados",
      titulo: "Características construtivas do principal local",
      tipo: "select",
      obrigatoria: true,
      categoria: "construcao",
      peso: 5,
      opcoes: [
        { label: "Superior", value: "superior", pontos: 1 },
        { label: "Sólida", value: "solida", pontos: 3 },
        { label: "Mista", value: "mista", pontos: 7 },
        { label: "Inferior", value: "inferior", pontos: 10 },
      ],
    },
    {
      codigo: "locais_pir_pur_larocha",
      secao: "Locais Segurados",
      titulo: "Há edificações mistas ou inferiores e/ou com mais de 25% da construção em PIR, PUR ou lã de rocha?",
      tipo: "select",
      obrigatoria: true,
      categoria: "construcao",
      peso: 4,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 8 },
      ],
    },
    {
      codigo: "locais_construcao_temporaria",
      secao: "Locais Segurados",
      titulo: "Existe mais de 15% do valor em risco em construções temporárias, como vinilona?",
      tipo: "select",
      obrigatoria: true,
      categoria: "construcao",
      peso: 4,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 9 },
      ],
    },
    {
      codigo: "locais_manutencao",
      secao: "Locais Segurados",
      titulo: "O prédio e o conteúdo possuem manutenção?",
      tipo: "select",
      obrigatoria: true,
      categoria: "manutencao",
      peso: 4,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 8 },
      ],
    },
    {
      codigo: "locais_tipo_manutencao",
      secao: "Locais Segurados",
      titulo: "A manutenção é terceirizada ou própria?",
      tipo: "select",
      categoria: "manutencao",
      peso: 2,
      opcoes: [
        { label: "Própria", value: "propria", pontos: 2 },
        { label: "Terceirizada", value: "terceirizada", pontos: 3 },
      ],
    },
    {
      codigo: "locais_maquina_critica",
      secao: "Locais Segurados",
      titulo: "Máquina ou equipamento principal cuja falha pode paralisar a operação",
      tipo: "textarea",
      categoria: "continuidade",
      peso: 5,
      placeholder: "Informe idade, origem, disponibilidade de peças e tempo estimado de paralisação",
    },
    {
      codigo: "locais_transito_terceiros",
      secao: "Locais Segurados",
      titulo: "Nível de trânsito ou permanência de terceiros",
      tipo: "select",
      obrigatoria: true,
      categoria: "terceiros",
      peso: 3,
      opcoes: [
        { label: "Baixo", value: "baixo", pontos: 1 },
        { label: "Médio", value: "medio", pontos: 4 },
        { label: "Alto", value: "alto", pontos: 7 },
      ],
    },

    {
      codigo: "protecional_avcb",
      secao: "Sistemas Protecionais",
      titulo: "Possui AVCB? Informe a validade se houver",
      tipo: "select",
      obrigatoria: true,
      categoria: "incendio",
      peso: 5,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 10 },
      ],
    },
    {
      codigo: "protecional_brigada",
      secao: "Sistemas Protecionais",
      titulo: "Possui Brigada de Incêndio com treinamento periódico?",
      tipo: "select",
      obrigatoria: true,
      categoria: "incendio",
      peso: 4,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 8 },
      ],
    },
    {
      codigo: "protecional_distancia_bombeiros",
      secao: "Sistemas Protecionais",
      titulo: "Distância do Corpo de Bombeiros mais próximo (km)",
      tipo: "number",
      obrigatoria: true,
      categoria: "incendio",
      peso: 3,
      placeholder: "Ex.: 5",
    },
    {
      codigo: "protecional_combate_incendio",
      secao: "Sistemas Protecionais",
      titulo: "Sistemas de detecção e combate a incêndio existentes",
      tipo: "multiselect",
      obrigatoria: true,
      categoria: "incendio",
      peso: 5,
      opcoes: [
        { label: "Extintores", value: "extintores", pontos: 1 },
        { label: "Hidrantes", value: "hidrantes", pontos: 1 },
        { label: "Mangotinhos", value: "mangotinhos", pontos: 1 },
        { label: "Sprinklers ou supressão automática", value: "sprinklers", pontos: 1 },
        { label: "Alarmes / detectores de fumaça", value: "alarmes", pontos: 1 },
      ],
    },
    {
      codigo: "protecional_roubo_furto",
      secao: "Sistemas Protecionais",
      titulo: "Proteções contra roubo e furto",
      tipo: "multiselect",
      categoria: "seguranca",
      peso: 4,
      opcoes: [
        { label: "Segurança patrimonial presencial", value: "seguranca_presencial", pontos: 1 },
        { label: "Alarme de intrusão", value: "alarme_intrusao", pontos: 1 },
        { label: "CFTV", value: "cftv", pontos: 1 },
        { label: "Sensores de presença", value: "sensores", pontos: 1 },
        { label: "Controle de acesso", value: "controle_acesso", pontos: 1 },
      ],
    },
    {
      codigo: "protecional_gerador_emergencia",
      secao: "Sistemas Protecionais",
      titulo: "Possui gerador de emergência?",
      tipo: "select",
      obrigatoria: true,
      categoria: "continuidade",
      peso: 3,
      opcoes: [
        { label: "Sim", value: "sim", pontos: 1 },
        { label: "Não", value: "nao", pontos: 6 },
      ],
    },

    {
      codigo: "experiencia_sinistros_5anos",
      secao: "Experiência",
      titulo: "Algum local sofreu sinistros nos últimos 5 anos?",
      tipo: "select",
      obrigatoria: true,
      categoria: "historico",
      peso: 5,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 9 },
      ],
    },
    {
      codigo: "experiencia_potencial_reclamacao",
      secao: "Experiência",
      titulo: "Existe fato ou circunstância que possa gerar reclamação?",
      tipo: "select",
      obrigatoria: true,
      categoria: "historico",
      peso: 4,
      opcoes: [
        { label: "Não", value: "nao", pontos: 1 },
        { label: "Sim", value: "sim", pontos: 8 },
      ],
    },
  ],
};

export function getQuestionnaireSections(type: QuestionnaireType) {
  const questions = QUESTIONNAIRES[type];
  const secoes = Array.from(new Set(questions.map((q) => q.secao)));

  return secoes.map((secao) => ({
    secao,
    perguntas: questions.filter((q) => q.secao === secao),
  }));
}